INSERT INTO driver_seasons (driver_id, season, constructor_id, rookie, price)
VALUES
--------------------------------------
/* ========= 2025 drivers ========= */
--------------------------------------

/* ========= INVICTA RACING ========= */
((SELECT id FROM drivers WHERE name = 'Leonardo Fornaroli'),
  2025,
  (SELECT id FROM constructors WHERE name = 'Invicta Racing'),
  0,
  4.5),
((SELECT id FROM drivers WHERE name = 'Roman Staněk'),
  2025,
  (SELECT id FROM constructors WHERE name = 'Invicta Racing'),
  0,
  4.0),

/* ========= CAMPOS RACING ========= */
((SELECT id FROM drivers WHERE name = 'Pepe Martí'),
  2025,
  (SELECT id FROM constructors WHERE name = 'Campos Racing'),
  0,
  3.8),
((SELECT id FROM drivers WHERE name = 'Arvid Lindblad'),
  2025,
  (SELECT id FROM constructors WHERE name = 'Campos Racing'),
  1,
  3.2),
((SELECT id FROM drivers WHERE name = 'Nikola Tsolov'),
  2025,
  (SELECT id FROM constructors WHERE name = 'Campos Racing'),
  0,
  4.2),

/* ========= MP MOTORSPORT ========= */
((SELECT id FROM drivers WHERE name = 'Oliver Goethe'),
  2025,
  (SELECT id FROM constructors WHERE name = 'MP Motorsport'),
  0,
  3.6),
((SELECT id FROM drivers WHERE name = 'Richard Verschoor'),
  2025,
  (SELECT id FROM constructors WHERE name = 'MP Motorsport'),
  0,
  4.4),

/* ========= HITECH TGR ========= */
((SELECT id FROM drivers WHERE name = 'Luke Browning'),
  2025,
  (SELECT id FROM constructors WHERE name = 'Hitech TGR'),
  0,
  4.1),
((SELECT id FROM drivers WHERE name = 'Dino Beganovic'),
  2025,
  (SELECT id FROM constructors WHERE name = 'Hitech TGR'),
  0,
  4.0),

/* ========= PREMA RACING ========= */
((SELECT id FROM drivers WHERE name = 'Sebastián Montoya'),
  2025,
  (SELECT id FROM constructors WHERE name = 'PREMA Racing'),
  0,
  3.9),
((SELECT id FROM drivers WHERE name = 'Gabriele Minì'),
  2025,
  (SELECT id FROM constructors WHERE name = 'PREMA Racing'),
  0,
  4.6),

/* ========= DAMS LUCAS OIL ========= */
((SELECT id FROM drivers WHERE name = 'Jak Crawford'),
  2025,
  (SELECT id FROM constructors WHERE name = 'DAMS Lucas Oil'),
  0,
  4.3),
((SELECT id FROM drivers WHERE name = 'Kush Maini'),
  2025,
  (SELECT id FROM constructors WHERE name = 'DAMS Lucas Oil'),
  0,
  3.7),

/* ========= ART GRAND PRIX ========= */
((SELECT id FROM drivers WHERE name = 'Victor Martins'),
  2025,
  (SELECT id FROM constructors WHERE name = 'ART Grand Prix'),
  0,
  4.8),
((SELECT id FROM drivers WHERE name = 'Ritomo Miyata'),
  2025,
  (SELECT id FROM constructors WHERE name = 'ART Grand Prix'),
  0,
  4.4),

/* ========= RODIN MOTORSPORT ========= */
((SELECT id FROM drivers WHERE name = 'Amaury Cordeel'),
  2025,
  (SELECT id FROM constructors WHERE name = 'Rodin Motorsport'),
  0,
  3.0),
((SELECT id FROM drivers WHERE name = 'Alexander Dunne'),
  2025,
  (SELECT id FROM constructors WHERE name = 'Rodin Motorsport'),
  1,
  2.8),
((SELECT id FROM drivers WHERE name = 'Martinius Stenshorne'),
  2025,
  (SELECT id FROM constructors WHERE name = 'Rodin Motorsport'),
  1,
  2.6),

/* ========= AIX RACING ========= */
((SELECT id FROM drivers WHERE name = 'Joshua Dürksen'),
  2025,
  (SELECT id FROM constructors WHERE name = 'AIX Racing'),
  0,
  3.5),
((SELECT id FROM drivers WHERE name = 'Cian Shields'),
  2025,
  (SELECT id FROM constructors WHERE name = 'AIX Racing'),
  0,
  2.5),

/* ========= TRIDENT ========= */
((SELECT id FROM drivers WHERE name = 'Sami Meguetounif'),
  2025,
  (SELECT id FROM constructors WHERE name = 'Trident'),
  1,
  2.9),
((SELECT id FROM drivers WHERE name = 'Laurens van Hoepen'),
  2025,
  (SELECT id FROM constructors WHERE name = 'Trident'),
  1,
  2.4),
((SELECT id FROM drivers WHERE name = 'Max Esterson'),
  2025,
  (SELECT id FROM constructors WHERE name = 'Trident'),
  0,
  2.2),
((SELECT id FROM drivers WHERE name = 'James Wharton'),
  2025,
  (SELECT id FROM constructors WHERE name = 'Trident'),
  1,
  2.0),
((SELECT id FROM drivers WHERE name = 'Tasanapol Inthraphuvasak'),
  2025,
  (SELECT id FROM constructors WHERE name = 'Trident'),
  1,
  1.8),

/* ========= VAN AMERSFOORT RACING ========= */
((SELECT id FROM drivers WHERE name = 'John Bennett'),
  2025,
  (SELECT id FROM constructors WHERE name = 'Van Amersfoort Racing'),
  1,
  1.9),
((SELECT id FROM drivers WHERE name = 'Rafael Villagómez'),
  2025,
  (SELECT id FROM constructors WHERE name = 'Van Amersfoort Racing'),
  0,
  3.1);
