INSERT OR IGNORE INTO drivers (name, number, rookie)
VALUES
('Rafael Câmara', 1, 1),
('Joshua Dürksen', 2, 0),
('Ritomo Miyata', 3, 0),
('Colton Hertan', 4, 1),
('Noel León', 5, 1),
('Nikola Tsolov', 6, 1),
('Dino Beganovic', 7, 0),
('Roman Bilinski', 8, 1),
('Gabriele Minì', 9, 0),
('Oliver Goethe', 10, 0),
('Sebastián Montoya', 11, 0),
('Mari Boya', 12, 1),
('Martinius Stenshorne', 14, 1),
('Alexander Dunne', 15, 0),
('Kush Maini', 16, 0),
('Tasanapol Inthraphuvasak', 17, 1),
('Emerson Fittipaldi', 20, 1),
('Cian Shields', 21, 0),
('Nicolás Varrone', 22, 1),
('Driver 23', 23, 1),
('Laurens van Hoepen', 24, 1),
('John Bennett', 25, 0);
