INSERT INTO qualifying_results (race_entry_id, position, status)
VALUES
(14, 1, 'OK'),  -- Alexander Dunne
(30, 2, 'OK'),  -- Victor Martins
(27, 3, 'OK'),  -- Richard Verschoor
(26, 4, 'OK'),  -- Arvid Lindblad
(9, 5, 'OK'),   -- Gabriele Minì
(15, 6, 'OK'),  -- Kush Maini
(23, 7, 'OK'),  -- Leonardo Fornaroli
(11, 8, 'OK'),  -- Sebastián Montoya
(29, 9, 'OK'),  -- Jak Crawford
(2, 10, 'OK'),  -- Joshua Dürksen
(28, 11, 'OK'), -- Luke Browning
(24, 12, 'OK'), -- Roman Staněk
(3, 13, 'OK'),  -- Ritomo Miyata
(31, 14, 'OK'), -- Amaury Cordeel
(7, 15, 'OK'),  -- Dino Beganovic
(32, 16, 'OK'), -- Sami Meguetounif
(10, 17, 'OK'), -- Oliver Goethe
(25, 18, 'OK'), -- Pepe Martí
(33, 19, 'OK'), -- Max Esterson
(22, 20, 'OK'), -- John Bennett
(18, 21, 'OK'); -- Cian Shields
