INSERT INTO qualifying_results (race_entry_id, position, status)
VALUES
(24, 1, 'OK'),   -- Roman Staněk
(23, 2, 'OK'),   -- Leonardo Fornaroli
(29, 3, 'OK'),   -- Jak Crawford
(28, 4, 'OK'),   -- Luke Browning
(2, 5, 'OK'),    -- Joshua Dürksen
(10, 6, 'OK'),   -- Oliver Goethe
(30, 7, 'OK'),   -- Victor Martins
(26, 8, 'OK'),   -- Arvid Lindblad
(14, 9, 'OK'),   -- Alexander Dunne
(25, 10, 'OK'),  -- Pepe Martí
(27, 11, 'OK'),  -- Richard Verschoor
(9, 12, 'OK'),   -- Gabriele Minì
(31, 13, 'OK'),  -- Amaury Cordeel
(7, 14, 'OK'),   -- Dino Beganovic
(22, 15, 'OK'),  -- John Bennett
(35, 16, 'OK'),  -- Rafael Villagómez
(3, 17, 'OK'),   -- Ritomo Miyata
(11, 18, 'OK'),  -- Sebastián Montoya
(32, 19, 'OK'),  -- Sami Meguetounif
(15, 20, 'OK'),  -- Kush Maini
(33, 21, 'OK'),  -- Max Esterson
(18, 22, 'OK');  -- Cian Shields
